Homework 5
suomiy/Movio pull request #4
Opened 2016-10-25 01:13 UTC by suomiy

2016-11-06 22:07 UTC, vandus commented on app/src/main/java/cz/muni/fi/pv256/movio2/fk410022/ui/adapter/MovieAdapter.java
> +                holder.detail.setBackgroundColor(Utils.addAlphaToColor(muted, 0.5f));
obrazky filmov nie su vidno. nie je to preto, ze sa farba settuje na holder, miesto na prislusny textview?

2016-11-06 22:08 UTC, vandus requested changes
aplikacia pada s FileNotFoundException

E/ImageLoader: https://image.tmdb.org/t/p/w700/7weWtCY6dy0djeWB80aE0dFfRni.jpg
                                                                             java.io.FileNotFoundException: https://image.tmdb.org/t/p/w700/7weWtCY6dy0djeWB80aE0dFfRni.jpg
                                                                                 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:242)
                                                                                 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                                 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                                                                                 at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromNetwork(BaseImageDownloader.java:124)
                                                                                 at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:88)...

2016-11-06 22:37 UTC, suomiy commented on app/src/main/java/cz/muni/fi/pv256/movio2/fk410022/ui/adapter/MovieAdapter.java
> +                holder.detail.setBackgroundColor(Utils.addAlphaToColor(muted, 0.5f));
Nemyslím, resp. u mě to funguje (i v emulátoru). Podle mě to má co dělat s tou vyjímkou, že se ty obrázky ani nestáhnou.

2016-11-06 23:40 UTC, suomiy commented
@vandus exception fixed

2016-11-13 22:29 UTC, vandus commented on app/src/main/java/cz/muni/fi/pv256/movio2/fk410022/MainActivity.java
> -    private boolean isTablet = false;
default hodnota booleanu je false

2016-11-13 22:30 UTC, vandus commented on app/src/main/java/cz/muni/fi/pv256/movio2/fk410022/MainActivity.java
> -            adapter = (films.length == 0) ? new MessageAdapter("Žádná data") : new MovieAdapter(films, this);
"zadna data" by si mal poriesit uz Adapter, nemali by sme to riesit my v UI.

2016-11-13 22:31 UTC, vandus commented on app/src/main/java/cz/muni/fi/pv256/movio2/fk410022/MainActivity.java
> -            adapter = (films.length == 0) ? new MessageAdapter("Žádná data") : new MovieAdapter(films, this);
tzn. sam si zisti ze ma 0 filmov a uz sa data stahovali, a tak zobrazi Empty View

2016-11-13 22:33 UTC, vandus commented on app/src/main/java/cz/muni/fi/pv256/movio2/fk410022/ui/adapter/MovieAdapter.java
> +                .getColor(context, R.color.palette_default), 0.5f));
pozadie by mohlo byt trosku menej transparentne, text je tazko citatelny.
keby ste dodrzali povodny design, vyzeralo by to krajsie s backdrop obrazkami roztiahnutymi na sirku :)

2016-11-13 22:35 UTC, vandus requested changes
Este poprosim pridat aspon jednu kategoriu. Hovorila som na hodine, ze tym, ze ste si niektori zvolili tuto cestu zobrazovat jednotlive kategorie pomocou horizontal scrollview, nevidite, ako sa sprava horizontalne scrollovanie spolu s vertikalnym a recyclerview v akcii.

2016-11-18 00:20 UTC, suomiy commented
@vandus all fixed 386e944

2016-11-18 00:24 UTC, suomiy commented on app/src/main/java/cz/muni/fi/pv256/movio2/fk410022/ui/adapter/MovieAdapter.java
> +                .getColor(context, R.color.palette_default), 0.5f));
Tak on Jonáš na cvikách říkal, že to můžem udělat i takto. Trochu jsem tu transparentnost změnil + přidal bold

2017-01-17 20:48 UTC, vandus approved these changes

2017-01-17 20:54 UTC, merged